  cobbler:
    restart: always
    image: admik/cobbler_oracle:v1.2
    networks:
      docker0:
        ipv4_address: 172.20.0.8
    volumes:
      - /srv/volumes/cobbler-2.8.0/var/lib/cobbler:/var/lib/cobbler:Z
      - /srv/volumes/cobbler-2.8.0/var/lib/cobbler/api_cobbler:/var/lib/cobbler/api_cobbler:Z
      - /srv/volumes/cobbler-2.8.0/var/www/cobbler:/var/www/cobbler:Z
      - /srv/volumes/cobbler-2.8.0/etc/cobbler:/etc/cobbler:Z
      - /srv/volumes/cobbler-2.8.0/etc/dhcp:/etc/dhcp:Z
      - /srv/volumes/cobbler-2.8.0/var/log:/var/log:Z
      - /srv/volumes/:/mnt:Z
      - /srv/volumes/cobbler-2.8.0/root/script.sh:/root/script.sh
    ports:
      - "67/udp:67/udp"
      - "68/udp:68/udp"
      - "69/udp:69/udp"
    environment:
      - ftp_proxy=
      - http_proxy=
      - https_proxy=
